#!/bin/bash

# cd to directory of this script, then call deploy.sh with directory name

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$SCRIPT_DIR"
d=$(basename "$SCRIPT_DIR")

"${PWD}/../bin/deploy.sh" "$d"
